name: tytydraco_xyz
description: The Flutter frontend app for the tytydraco.xyz website.
publish_to: 'none'
repository: https://github.com/tytydraco/tytydraco_xyz
homepage: https://tytydraco.xyz
version: 1.0.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
  fonts:
    - family: Source Code Pro
      fonts:
        - asset: fonts/SourceCodePro-Regular.otf

flutter_icons:
  web: true
  image_path: 'assets/logo_circle_dark.png'

basil:
  get:
    cmds: [ 'flutter pub get' ]
  icon:
    cmds: [ 'flutter pub run flutter_launcher_icons_maker:main' ]
  build:
    cmds:
      - 'flutter build web --release --web-renderer html'
      - 'git add build/web/'
      - 'bash -c "git commit -sam \"Build web: $(date)\""'
  publish:
    cmds:
      - 'firebase deploy'
      - 'git push'
