name: tytydraco_xyz
description: The Flutter frontend app for the tytydraco.xyz website.
publish_to: 'none'
version: 1.0.0
repository: https://www.github.com/tytydraco/tytydraco_xyz
homepage: https://www.tytydraco.xyz

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  basil: ^1.1.0+1
  flutter_launcher_icons_maker: ^0.10.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

flutter_icons:
  web: true
  image_path: 'assets/logo.png'

basil:
  get:
    cmds: [ 'flutter pub get' ]
  icon:
    cmds: [ 'flutter pub run flutter_launcher_icons_maker:main' ]
  build:
    cmds: [ 'flutter build web --release' ]
  publish:
    cmds: [ 'bash -c "cd build/web/ && echo TODO"' ]
